_wandb:
    value:
        cli_version: 0.21.0
        e:
            w5uiqfst2kqt0x53acqlqln4aiacj53g:
                args:
                    - --data_path
                    - data/croissants.yaml
                    - --epochs
                    - "200"
                    - --freeze
                    - "2"
                codePath: src/finetune_YOLO.py
                codePathLocal: src/finetune_YOLO.py
                cpu_count: 14
                cpu_count_logical: 14
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "532608356352"
                        used: "169411997696"
                email: declan.k.hoban@gmail.com
                executable: /home/decla_5ay7wb/RIPS25-AnalogDevices-ObjectDetection/env/bin/python
                git:
                    commit: e2d9a447a57b8e1005db0a469871e6b9e72a0f6e
                    remote: https://github.com/Vikhyat2603/RIPS25-AnalogDevices-ObjectDetection.git
                gpu: Quadro RTX 6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: Quadro RTX 6000
                      uuid: GPU-b8ffde4c-2ad9-e0a7-1082-3456fede15d0
                host: 104-171-203-214
                memory:
                    total: "48400441344"
                os: Linux-6.8.0-52-generic-x86_64-with-glibc2.35
                program: /home/decla_5ay7wb/RIPS25-AnalogDevices-ObjectDetection/src/finetune_YOLO.py
                python: CPython 3.10.12
                root: /home/decla_5ay7wb/RIPS25-AnalogDevices-ObjectDetection
                startedAt: "2025-07-03T23:38:09.677488Z"
                writerId: w5uiqfst2kqt0x53acqlqln4aiacj53g
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
                - 41
            "3":
                - 13
                - 16
                - 61
            "4": 3.10.12
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
agnostic_nms:
    value: false
amp:
    value: true
augment:
    value: false
auto_augment:
    value: randaugment
batch:
    value: 16
bgr:
    value: 0
box:
    value: 7.5
cache:
    value: false
cfg:
    value: null
classes:
    value: null
close_mosaic:
    value: 10
cls:
    value: 0.5
conf:
    value: null
copy_paste:
    value: 0
copy_paste_mode:
    value: flip
cos_lr:
    value: false
cutmix:
    value: 0
data:
    value: data/croissants.yaml
degrees:
    value: 0
deterministic:
    value: true
device:
    value: null
dfl:
    value: 1.5
dnn:
    value: false
dropout:
    value: 0
dynamic:
    value: false
embed:
    value: null
epochs:
    value: 200
erasing:
    value: 0.4
exist_ok:
    value: false
fliplr:
    value: 0.5
flipud:
    value: 0
format:
    value: torchscript
fraction:
    value: 1
freeze:
    value: 2
half:
    value: false
hsv_h:
    value: 0.015
hsv_s:
    value: 0.7
hsv_v:
    value: 0.4
imgsz:
    value: 640
int8:
    value: false
iou:
    value: 0.7
keras:
    value: false
kobj:
    value: 1
line_width:
    value: null
lr0:
    value: 0.01
lrf:
    value: 0.01
mask_ratio:
    value: 4
max_det:
    value: 300
mixup:
    value: 0
mode:
    value: train
model:
    value: yolo11n.pt
momentum:
    value: 0.937
mosaic:
    value: 1
multi_scale:
    value: false
name:
    value: train3
nbs:
    value: 64
nms:
    value: false
opset:
    value: null
optimize:
    value: false
optimizer:
    value: auto
overlap_mask:
    value: true
patience:
    value: 100
perspective:
    value: 0
plots:
    value: true
pose:
    value: 12
pretrained:
    value: true
profile:
    value: false
project:
    value: runs/croissants
rect:
    value: false
resume:
    value: false
retina_masks:
    value: false
save:
    value: true
save_conf:
    value: false
save_crop:
    value: false
save_dir:
    value: runs/croissants/train3
save_frames:
    value: false
save_json:
    value: false
save_period:
    value: -1
save_txt:
    value: false
scale:
    value: 0.5
seed:
    value: 0
shear:
    value: 0
show:
    value: false
show_boxes:
    value: true
show_conf:
    value: true
show_labels:
    value: true
simplify:
    value: true
single_cls:
    value: false
source:
    value: null
split:
    value: val
stream_buffer:
    value: false
task:
    value: detect
time:
    value: null
tracker:
    value: botsort.yaml
translate:
    value: 0.1
val:
    value: true
verbose:
    value: true
vid_stride:
    value: 1
visualize:
    value: false
warmup_bias_lr:
    value: 0.1
warmup_epochs:
    value: 3
warmup_momentum:
    value: 0.8
weight_decay:
    value: 0.0005
workers:
    value: 8
workspace:
    value: null
